"""
Generate Diff Report Command

Produces an HTML comparison report between two migration runs
(typically dry-run vs live-run).
"""
from dataclasses import dataclass

from domain.services.diff_service import MigrationDiff


_DIFF_TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Migration Diff Report</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }}
h1 {{ color: #1a1a2e; }}
.verdict {{ padding: 1rem; border-radius: 8px; margin: 1rem 0; font-weight: 600; }}
.verdict.pass {{ background: #e8f5e9; color: #2e7d32; }}
.verdict.fail {{ background: #ffebee; color: #c62828; }}
.summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin: 1.5rem 0; }}
.card {{ background: #f8f9fa; border-radius: 8px; padding: 1rem; text-align: center; }}
.card .number {{ font-size: 1.5rem; font-weight: 700; }}
.card .label {{ color: #666; font-size: 0.85rem; }}
.positive {{ color: #2e7d32; }} .negative {{ color: #c62828; }} .neutral {{ color: #666; }}
table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
th, td {{ padding: 0.6rem 0.8rem; border-bottom: 1px solid #e0e0e0; text-align: left; }}
th {{ background: #f0f0f0; }}
footer {{ margin-top: 2rem; color: #999; font-size: 0.8rem; }}
</style></head><body>
<h1>Migration Diff: {baseline_label} vs {current_label}</h1>
<div class="verdict {verdict_class}">{verdict_text}</div>
<div class="summary">
  <div class="card"><div class="number {extracted_class}">{extracted_delta:+d}</div><div class="label">Extracted</div></div>
  <div class="card"><div class="number {loaded_class}">{loaded_delta:+d}</div><div class="label">Loaded</div></div>
  <div class="card"><div class="number {quarantined_class}">{quarantined_delta:+d}</div><div class="label">Quarantined</div></div>
  <div class="card"><div class="number {duration_class}">{duration_delta:+.1f}s</div><div class="label">Duration</div></div>
</div>
<h2>Per-Object Comparison</h2>
<table>
<tr><th>Object</th><th>{baseline_label} Total</th><th>{current_label} Total</th>
<th>{baseline_label} Success</th><th>{current_label} Success</th>
<th>New Errors</th><th>Resolved</th></tr>
{batch_rows}
</table>
<footer>Generated by Nexus Migration Accelerator v1.0</footer>
</body></html>"""


@dataclass
class GenerateDiffReportCommand:
    diff: MigrationDiff

    def execute(self) -> str:
        d = self.diff

        verdict_class = "fail" if d.is_regression else "pass"
        verdict_text = (
            "REGRESSION DETECTED: new errors or increased quarantines"
            if d.is_regression
            else "No regressions detected: safe to proceed with live migration"
        )

        batch_rows = ""
        for bd in d.batch_diffs:
            err_class = "negative" if bd.new_errors > 0 else "neutral"
            res_class = "positive" if bd.resolved_errors > 0 else "neutral"
            batch_rows += (
                f"<tr><td>{bd.object_type}</td>"
                f"<td>{bd.baseline_total}</td><td>{bd.current_total}</td>"
                f"<td>{bd.baseline_success}</td><td>{bd.current_success}</td>"
                f"<td class='{err_class}'>{bd.new_errors}</td>"
                f"<td class='{res_class}'>{bd.resolved_errors}</td></tr>\n"
            )

        return _DIFF_TEMPLATE.format(
            baseline_label=d.baseline_label,
            current_label=d.current_label,
            verdict_class=verdict_class,
            verdict_text=verdict_text,
            extracted_delta=d.extracted_delta,
            extracted_class=self._delta_class(d.extracted_delta, positive_is_good=True),
            loaded_delta=d.loaded_delta,
            loaded_class=self._delta_class(d.loaded_delta, positive_is_good=True),
            quarantined_delta=d.quarantined_delta,
            quarantined_class=self._delta_class(d.quarantined_delta, positive_is_good=False),
            duration_delta=d.duration_delta,
            duration_class=self._delta_class(-d.duration_delta, positive_is_good=True),
            batch_rows=batch_rows,
        )

    @staticmethod
    def _delta_class(delta: int | float, positive_is_good: bool) -> str:
        if delta == 0:
            return "neutral"
        if delta > 0:
            return "positive" if positive_is_good else "negative"
        return "negative" if positive_is_good else "positive"
