"""
Generate Report Command

Produces an HTML summary report from a MigrationSummary,
including remediation recommendations for common error patterns.
"""
from dataclasses import dataclass
from html import escape

from domain.services.remediation_service import RemediationService
from domain.value_objects.migration_result import MigrationSummary, RecordStatus


_REPORT_TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Migration Report</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 960px; margin: 2rem auto; padding: 0 1rem; }}
h1 {{ color: #1a1a2e; }}
.summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin: 1.5rem 0; }}
.card {{ background: #f8f9fa; border-radius: 8px; padding: 1.2rem; text-align: center; }}
.card .number {{ font-size: 2rem; font-weight: 700; color: #16213e; }}
.card .label {{ color: #666; font-size: 0.9rem; }}
table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
th, td {{ padding: 0.6rem 0.8rem; border-bottom: 1px solid #e0e0e0; text-align: left; }}
th {{ background: #f0f0f0; }}
.success {{ color: #2e7d32; }} .warning {{ color: #f57f17; }} .error {{ color: #c62828; }}
.remediation {{ border-left: 4px solid #1565c0; background: #e3f2fd; padding: 1rem 1.2rem; margin: 0.8rem 0; border-radius: 0 6px 6px 0; }}
.remediation.critical {{ border-left-color: #c62828; background: #ffebee; }}
.remediation.warning {{ border-left-color: #f57f17; background: #fff8e1; }}
.remediation .pattern {{ font-weight: 700; margin-bottom: 0.3rem; }}
.remediation .count {{ font-size: 0.85rem; color: #666; }}
.remediation .rec {{ margin-top: 0.5rem; }}
.affected {{ font-size: 0.8rem; color: #888; margin-top: 0.4rem; word-break: break-all; }}
footer {{ margin-top: 2rem; color: #999; font-size: 0.8rem; }}
</style></head><body>
<h1>Salesforce &rarr; Nexus Migration Report</h1>
<div class="summary">
  <div class="card"><div class="number">{total_extracted}</div><div class="label">Extracted</div></div>
  <div class="card"><div class="number">{total_loaded}</div><div class="label">Loaded</div></div>
  <div class="card"><div class="number">{total_quarantined}</div><div class="label">Quarantined</div></div>
  <div class="card"><div class="number">{duration:.1f}s</div><div class="label">Duration</div></div>
</div>
<h2>Per-Object Breakdown</h2>
<table>
<tr><th>Object</th><th>Total</th><th class="success">Success</th><th class="warning">Warning</th><th class="error">Error</th><th>Quarantined</th></tr>
{batch_rows}
</table>
{remediation_section}
{quarantine_section}
{warnings_section}
<footer>Generated by Nexus Migration Accelerator v1.0</footer>
</body></html>"""


@dataclass
class GenerateReportCommand:
    summary: MigrationSummary

    def execute(self) -> str:
        batch_rows = ""
        all_quarantined = []
        for b in self.summary.batches:
            batch_rows += (
                f"<tr><td>{b.object_type}</td><td>{b.total}</td>"
                f"<td class='success'>{b.success_count}</td>"
                f"<td class='warning'>{b.warning_count}</td>"
                f"<td class='error'>{b.error_count}</td>"
                f"<td>{b.quarantined_count}</td></tr>\n"
            )
            all_quarantined.extend(
                r for r in b.record_results if r.status == RecordStatus.QUARANTINED
            )

        # Remediation recommendations
        remediation_section = self._build_remediation_section()

        quarantine_section = ""
        if all_quarantined:
            rows = "".join(
                f"<tr><td>{escape(r.object_type)}</td><td>{escape(r.salesforce_id)}</td>"
                f"<td>{escape(r.message)}</td></tr>"
                for r in all_quarantined[:100]
            )
            quarantine_section = (
                f"<h2>Quarantined Records ({len(all_quarantined)})</h2>"
                f"<table><tr><th>Type</th><th>SF ID</th><th>Reason</th></tr>{rows}</table>"
            )

        warnings_section = ""
        if self.summary.warnings:
            items = "".join(f"<li>{escape(w)}</li>" for w in self.summary.warnings[:50])
            warnings_section = f"<h2>Warnings</h2><ul>{items}</ul>"

        return _REPORT_TEMPLATE.format(
            total_extracted=self.summary.total_extracted,
            total_loaded=self.summary.total_loaded,
            total_quarantined=self.summary.total_quarantined,
            duration=self.summary.duration_seconds,
            batch_rows=batch_rows,
            remediation_section=remediation_section,
            quarantine_section=quarantine_section,
            warnings_section=warnings_section,
        )

    def _build_remediation_section(self) -> str:
        service = RemediationService()
        remediations = service.analyse(self.summary)
        if not remediations:
            return ""

        items = []
        for r in remediations:
            affected = ""
            if r.affected_ids:
                ids = ", ".join(r.affected_ids[:10])
                suffix = f" ... and {len(r.affected_ids) - 10} more" if len(r.affected_ids) > 10 else ""
                affected = f'<div class="affected">Affected IDs: {escape(ids)}{suffix}</div>'

            items.append(
                f'<div class="remediation {r.severity}">'
                f'<div class="pattern">{escape(r.pattern)} ({r.count})</div>'
                f'<div class="rec">{escape(r.recommendation)}</div>'
                f'{affected}</div>'
            )

        return f'<h2>Recommended Remediation Steps</h2>\n{"".join(items)}'
