"""
Generate Report Command

Produces an HTML summary report from a MigrationSummary.
"""
from dataclasses import dataclass

from domain.value_objects.migration_result import MigrationSummary, RecordStatus


_REPORT_TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Migration Report</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }}
h1 {{ color: #1a1a2e; }}
.summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin: 1.5rem 0; }}
.card {{ background: #f8f9fa; border-radius: 8px; padding: 1.2rem; text-align: center; }}
.card .number {{ font-size: 2rem; font-weight: 700; color: #16213e; }}
.card .label {{ color: #666; font-size: 0.9rem; }}
table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
th, td {{ padding: 0.6rem 0.8rem; border-bottom: 1px solid #e0e0e0; text-align: left; }}
th {{ background: #f0f0f0; }}
.success {{ color: #2e7d32; }} .warning {{ color: #f57f17; }} .error {{ color: #c62828; }}
footer {{ margin-top: 2rem; color: #999; font-size: 0.8rem; }}
</style></head><body>
<h1>Salesforce → Nexus Migration Report</h1>
<div class="summary">
  <div class="card"><div class="number">{total_extracted}</div><div class="label">Extracted</div></div>
  <div class="card"><div class="number">{total_loaded}</div><div class="label">Loaded</div></div>
  <div class="card"><div class="number">{total_quarantined}</div><div class="label">Quarantined</div></div>
  <div class="card"><div class="number">{duration:.1f}s</div><div class="label">Duration</div></div>
</div>
<h2>Per-Object Breakdown</h2>
<table>
<tr><th>Object</th><th>Total</th><th class="success">Success</th><th class="warning">Warning</th><th class="error">Error</th><th>Quarantined</th></tr>
{batch_rows}
</table>
{quarantine_section}
{warnings_section}
<footer>Generated by Nexus Migration Accelerator v1.0</footer>
</body></html>"""


@dataclass
class GenerateReportCommand:
    summary: MigrationSummary

    def execute(self) -> str:
        batch_rows = ""
        all_quarantined = []
        for b in self.summary.batches:
            batch_rows += (
                f"<tr><td>{b.object_type}</td><td>{b.total}</td>"
                f"<td class='success'>{b.success_count}</td>"
                f"<td class='warning'>{b.warning_count}</td>"
                f"<td class='error'>{b.error_count}</td>"
                f"<td>{b.quarantined_count}</td></tr>\n"
            )
            all_quarantined.extend(
                r for r in b.record_results if r.status == RecordStatus.QUARANTINED
            )

        quarantine_section = ""
        if all_quarantined:
            rows = "".join(
                f"<tr><td>{r.object_type}</td><td>{r.salesforce_id}</td><td>{r.message}</td></tr>"
                for r in all_quarantined[:100]
            )
            quarantine_section = (
                f"<h2>Quarantined Records ({len(all_quarantined)})</h2>"
                f"<table><tr><th>Type</th><th>SF ID</th><th>Reason</th></tr>{rows}</table>"
            )

        warnings_section = ""
        if self.summary.warnings:
            items = "".join(f"<li>{w}</li>" for w in self.summary.warnings[:50])
            warnings_section = f"<h2>Warnings</h2><ul>{items}</ul>"

        return _REPORT_TEMPLATE.format(
            total_extracted=self.summary.total_extracted,
            total_loaded=self.summary.total_loaded,
            total_quarantined=self.summary.total_quarantined,
            duration=self.summary.duration_seconds,
            batch_rows=batch_rows,
            quarantine_section=quarantine_section,
            warnings_section=warnings_section,
        )
